tabs:
  general:
    display: 'General'
    sections:
      -
        fields:
          -
            handle: forms
            field:
              fields:
                -
                  handle: form
                  field:
                    display: Form
                    instructions: 'The form you want to process ActiveCampaign submissions for.'
                    type: form
                    max_items: 1
                    mode: select
                    width: 33
                -
                  handle: email_field
                  field:
                    display: 'Email Field'
                    instructions: 'The field that contains the email address of the subscriber.'
                    type: form_fields
                    max_items: 1
                    default: email
                    width: 33
                -
                  handle: consent_field
                  field:
                    display: 'Consent Field'
                    instructions: 'The field that contains the consent of the subscriber.'
                    type: form_fields
                    width: 33
                -
                  handle: list_id
                  field:
                    display: 'List ID'
                    instructions: 'The list you want to add the subscriber to.'
                    type: activecampaign_list
                    mode: select
                    max_items: 1
                    validate: 'required'
                    width: 50
                -
                  handle: tag
                  field:
                    display: 'Tag'
                    instructions: 'The tag you want to add to the subscriber.'
                    type: activecampaign_tag
                    mode: select
                    max_items: 1
                    width: 50
                -
                  handle: merge_fields
                  field:
                    fields:
                      -
                        handle: field_name
                        field:
                          input_type: text
                          display: Form Field
                          type: form_fields
                          icon: text
                          listable: hidden
                      -
                        handle: activecampaign_field
                        field:
                          input_type: text
                          display: 'Merge Field'
                          type: activecampaign_merge_fields
                          max_items: 1
                          icon: text
                          listable: hidden
                    mode: table
                    reorderable: true
                    display: 'Merge Fields'
                    instructions: 'Add the form fields you want to map to ActiveCampaign fields.'
                    type: grid
                    icon: grid
                    add_row: 'Add Merge Field'
                    listable: hidden
                    fullscreen: false
              display: 'Form Settings'
              instructions: 'Add the forms you want to process ActiveCampaign submissions for.'
              type: grid
              mode: stacked
              add_row: 'Add Form'
              fullscreen: false
